"""Research progress is durable across both worker database execution paths."""

from __future__ import annotations

import asyncio
import json

import pytest
import test_runs_api
from sqlalchemy import create_engine, select, text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.orm import sessionmaker

from browser_use_agent.agent.browser_port import FakeBrowserPort
from browser_use_agent.agent.controls import reset_control_hub_for_tests
from browser_use_agent.agent.worker import RunWorker
from browser_use_agent.db.migrate import upgrade_head
from browser_use_agent.db.models import AgentEvent, Run
from browser_use_agent.policy.actions import BrowserObservation
from browser_use_agent.policy.jev_client import FakeDecision, FakeJevClient
from browser_use_agent.policy.text_llm import FakeTextLLMClient, TextLLMPrompt, TextLLMResult
from browser_use_agent.services import runs as run_service

postgres_url = test_runs_api.postgres_url


class EvidenceTextClient(FakeTextLLMClient):
    """Return synthesis citing the actual IDs generated by the application."""

    async def complete_structured(self, prompt: TextLLMPrompt) -> TextLLMResult:
        """Read provided evidence IDs rather than inventing a citation."""
        payload = json.loads(prompt.user)
        if payload["purpose"] == "synthesis":
            content = {
                "fields": {
                    "location": {
                        "answer": "London",
                        "status": "found",
                        "evidence_ids": [payload["evidence"][0]["id"]],
                    },
                    "refund": {"answer": None, "status": "missing", "evidence_ids": []},
                }
            }
            return TextLLMResult(text=json.dumps(content), model="fake-text", latency_ms=0)
        return await super().complete_structured(prompt)


@pytest.mark.parametrize("async_db", [False, True], ids=["sync-session", "async-session"])
@pytest.mark.parametrize("invalid_json", [False, True], ids=["valid-result", "invalid-extraction"])
async def test_worker_persists_research_transaction(
    postgres_url: str, async_db: bool, invalid_json: bool
) -> None:
    """Both worker paths save sourced evidence and audit it before success."""
    reset_control_hub_for_tests()
    upgrade_head(database_url=postgres_url)
    engine = create_engine(postgres_url)
    factory = sessionmaker(bind=engine, expire_on_commit=False)
    with engine.begin() as connection:
        connection.execute(text("TRUNCATE runs CASCADE"))
    with factory() as session:
        run = run_service.create_run(
            session,
            "Research location and refund",
            output_fields={"location": "City", "refund": "Refund window"},
        )
        session.commit()
        run_id = run.id
    async_engine = create_async_engine(postgres_url) if async_db else None
    worker_factory = (
        async_sessionmaker(async_engine, expire_on_commit=False) if async_db else factory
    )
    first = BrowserObservation(
        url="https://example.test/source",
        title="Original source",
        page_text="Our headquarters are in London.",
    )
    later = BrowserObservation(
        url="https://example.test/unrelated",
        title="Later page",
        page_text="Unrelated page.",
        suggested_urls=["https://example.test/unrelated"],
    )
    browser = FakeBrowserPort([first, first, later])
    extraction = json.dumps(
        {
            "findings": [
                {
                    "field": "location",
                    "value": "London",
                    "excerpt": "Our headquarters are in London.",
                }
            ]
        }
    )
    client = EvidenceTextClient(texts=["not JSON" if invalid_json else extraction])
    worker = RunWorker(
        worker_factory,
        jev_factory=lambda: FakeJevClient(
            [
                FakeDecision(operation="EXTRACT"),
                FakeDecision(operation="NAVIGATE", navigate_url="https://example.test/unrelated"),
                FakeDecision(operation="DONE"),
            ]
        ),
        text_llm_factory=lambda: client,
        browser_port_factory=lambda *_: browser,
        checkpoint=lambda *_: None,
        screenshot=lambda *_: None,
    )
    try:
        task = await worker.start_run(run_id)
        await asyncio.wait_for(task, timeout=10)
        with factory() as session:
            saved = session.get(Run, run_id)
            events = list(
                session.scalars(
                    select(AgentEvent).where(AgentEvent.run_id == run_id).order_by(AgentEvent.seq)
                )
            )
            event_types = [event.event_type for event in events]
            if invalid_json:
                assert saved.status == "failed"
                assert saved.metadata_.get("result") is None
                assert not saved.metadata_.get("evidence")
                assert "model_call_failed" in event_types
                assert "research_result" not in event_types
            else:
                assert saved.status == "succeeded"
                evidence = saved.metadata_["evidence"]
                assert len(evidence) == 1
                assert evidence[0]["url"] == first.url
                answer = saved.metadata_["result"]["location"]
                assert answer["sources"][0]["evidence_id"] == evidence[0]["id"]
                assert answer["sources"][0]["url"] == first.url
                assert saved.metadata_["result"]["refund"] == {
                    "answer": None,
                    "status": "missing",
                    "sources": [],
                }
                assert (
                    event_types.index("research_evidence")
                    < event_types.index("research_result")
                    < event_types.index("run_succeeded")
                )
                assert (
                    next(
                        event for event in events if event.event_type == "research_evidence"
                    ).metadata_["evidence"]
                    == evidence
                )
    finally:
        if async_engine is not None:
            await async_engine.dispose()
        engine.dispose()
        reset_control_hub_for_tests()


def test_pause_resume_retains_research_and_retry_clears_current_state(postgres_url: str) -> None:
    """Lifecycle controls retain findings until failed research is retried."""
    reset_control_hub_for_tests()
    upgrade_head(database_url=postgres_url)
    engine = create_engine(postgres_url)
    with engine.begin() as connection:
        connection.execute(text("TRUNCATE runs CASCADE"))
    with sessionmaker(bind=engine)() as session:
        run = run_service.create_run(session, "Research", output_fields={"location": "City"})
        run.status = "running"
        research = {
            "evidence": [{"id": "e1", "value": "London"}],
            "research_pages": [{"url": "https://example.test"}],
            "result": {"location": {"answer": "London"}},
        }
        run.metadata_ = {**run.metadata_, **research}
        session.commit()
        run_service.pause_run(session, run.id)
        session.commit()
        run_service.resume_run(session, run.id)
        session.commit()
        session.refresh(run)
        assert all(run.metadata_[key] == value for key, value in research.items())
        before = list(session.scalars(select(AgentEvent.id).where(AgentEvent.run_id == run.id)))
        run.status = "failed"
        session.commit()
        run_service.retry_run(session, run.id)
        session.commit()
        session.refresh(run)
        assert run.status == "queued"
        assert run.metadata_["output_fields"] == {"location": "City"}
        assert run.metadata_["evidence"] == []
        assert run.metadata_["research_pages"] == []
        assert run.metadata_["result"] is None
        after = list(session.scalars(select(AgentEvent.id).where(AgentEvent.run_id == run.id)))
        assert set(before) < set(after)
    engine.dispose()
    reset_control_hub_for_tests()


@pytest.mark.parametrize("async_db", [False, True], ids=["sync-session", "async-session"])
async def test_each_extraction_persists_all_progress(postgres_url: str, async_db: bool) -> None:
    """A later extraction updates JSON metadata independently of final synthesis."""
    reset_control_hub_for_tests()
    upgrade_head(database_url=postgres_url)
    engine = create_engine(postgres_url)
    factory = sessionmaker(bind=engine, expire_on_commit=False)
    with engine.begin() as connection:
        connection.execute(text("TRUNCATE runs CASCADE"))
    with factory() as session:
        run = run_service.create_run(
            session,
            "Collect two fields",
            output_fields={"location": "City", "refund": "Refund window"},
        )
        session.commit()
        run_id = run.id
    async_engine = create_async_engine(postgres_url) if async_db else None
    worker_factory = (
        async_sessionmaker(async_engine, expire_on_commit=False) if async_db else factory
    )
    first = BrowserObservation(
        url="https://example.test/about", title="About", page_text="We are in London."
    )
    second = BrowserObservation(
        url="https://example.test/refunds",
        title="Refunds",
        page_text="Refunds are available for 30 days.",
    )
    browser = FakeBrowserPort([first, second, second])
    client = FakeTextLLMClient(
        texts=[
            json.dumps(
                {"findings": [{"field": "location", "value": "London", "excerpt": first.page_text}]}
            ),
            json.dumps(
                {"findings": [{"field": "refund", "value": "30 days", "excerpt": second.page_text}]}
            ),
            "invalid final JSON",
        ]
    )
    worker = RunWorker(
        worker_factory,
        jev_factory=lambda: FakeJevClient(
            [
                FakeDecision(operation="EXTRACT"),
                FakeDecision(operation="EXTRACT"),
                FakeDecision(operation="DONE"),
            ]
        ),
        text_llm_factory=lambda: client,
        browser_port_factory=lambda *_: browser,
        checkpoint=lambda *_: None,
        screenshot=lambda *_: None,
    )
    try:
        await asyncio.wait_for(await worker.start_run(run_id), timeout=10)
        with factory() as session:
            saved = session.get(Run, run_id)
            assert saved.status == "failed"
            assert saved.metadata_["result"] is None
            assert {item["field"] for item in saved.metadata_["evidence"]} == {"location", "refund"}
            assert {item["url"] for item in saved.metadata_["research_pages"]} == {
                first.url,
                second.url,
            }
            events = list(
                session.scalars(
                    select(AgentEvent)
                    .where(
                        AgentEvent.run_id == run_id, AgentEvent.event_type == "research_evidence"
                    )
                    .order_by(AgentEvent.seq)
                )
            )
            assert len(events) == 2
            assert {item["id"] for item in saved.metadata_["evidence"]} == {
                event.metadata_["evidence"][0]["id"] for event in events
            }
    finally:
        if async_engine is not None:
            await async_engine.dispose()
        engine.dispose()
        reset_control_hub_for_tests()
