"""Append-only audit writer and per-run hash-chain verification."""

from browser_use_agent.audit.browser_actions import BrowserActionWriter
from browser_use_agent.audit.checkpoints import (
    CHECKPOINT_SCHEMA_VERSION,
    CheckpointReason,
    CheckpointResult,
    CheckpointSettings,
    CheckpointWriter,
    decide_checkpoint,
    load_checkpoint_payload,
    load_checkpoint_settings,
    observation_from_checkpoint,
)
from browser_use_agent.audit.costs import (
    ModelPrice,
    aggregate_costs,
    estimate_model_cost,
    load_model_prices,
    recent_cost_summary,
    run_cost,
)
from browser_use_agent.audit.hashchain import (
    GENESIS_PREV_HASH,
    canonicalize_event_fields,
    canonicalize_value,
    compute_event_hash,
    event_hash_fields,
    verify_events_chain,
    verify_run_chain,
)
from browser_use_agent.audit.model_calls import ModelCallWriter
from browser_use_agent.audit.screenshots import (
    DESTRUCTIVE_ACTION_KINDS,
    SCREENSHOT_ARTIFACT_KIND,
    SCREENSHOT_EVENT_TYPE,
    ScreenshotFormat,
    ScreenshotReason,
    ScreenshotResult,
    ScreenshotSettings,
    ScreenshotWriter,
    decide_screenshot,
    encode_screenshot,
    is_destructive_action,
    load_screenshot_settings,
)
from browser_use_agent.audit.writer import (
    Actor,
    AuditWriter,
    AuditWriterError,
    set_append_hook,
)

__all__ = [
    "CHECKPOINT_SCHEMA_VERSION",
    "DESTRUCTIVE_ACTION_KINDS",
    "GENESIS_PREV_HASH",
    "SCREENSHOT_ARTIFACT_KIND",
    "SCREENSHOT_EVENT_TYPE",
    "Actor",
    "AuditWriter",
    "AuditWriterError",
    "BrowserActionWriter",
    "CheckpointReason",
    "CheckpointResult",
    "CheckpointSettings",
    "CheckpointWriter",
    "ModelCallWriter",
    "ModelPrice",
    "ScreenshotFormat",
    "ScreenshotReason",
    "ScreenshotResult",
    "ScreenshotSettings",
    "ScreenshotWriter",
    "aggregate_costs",
    "canonicalize_event_fields",
    "canonicalize_value",
    "compute_event_hash",
    "decide_checkpoint",
    "decide_screenshot",
    "encode_screenshot",
    "estimate_model_cost",
    "event_hash_fields",
    "is_destructive_action",
    "load_checkpoint_payload",
    "load_checkpoint_settings",
    "load_model_prices",
    "load_screenshot_settings",
    "observation_from_checkpoint",
    "recent_cost_summary",
    "run_cost",
    "set_append_hook",
    "verify_events_chain",
    "verify_run_chain",
]
